### ISSUE TITLE
Huber Loss

### ISSUE THREAD

**Issue by pratikwatwani** [NannyML/The-Little-Book-of-ML-Metrics#105]
**Huber Loss**

**Metric's category - Regression**

**Metrics formula**
![Huber Loss](https://github.com/user-attachments/assets/17d8de77-1766-4f1c-8576-fe18c22759f2)

**Describe the metrics use cases, and any relevant references.**
1. Useful in regression problems where you want to minimize the effect of the outliers.
2. Unlike MSE, which penalizes outliers heavily, Huber Loss, will give a balanced penalty between MSE and MAE

**Comment by santiviquez** [comment]
Is Huber Loss used for model evaluation? I only recall it being used as a loss function in optimization.

**Comment by pratikwatwani** [comment]
Yes, It’s primarily used during model optimization, particularly when dealing with outliers to adjust the model’s parameters

**Comment by santiviquez** [comment]
Yeah, in that case, I'm not sure if it makes sense to include it as a metric in the book. To define the book's scope, the metrics we cover should ideally be evaluation metrics, not just loss functions.

**Comment by pratikwatwani** [comment]
Got it, sounds good. Thank you for clarifying!
