### ISSUE TITLE
Installing strawberry-perl

### ISSUE THREAD

**Issue by AnshTanwar** [NannyML/The-Little-Book-of-ML-Metrics#108]
**Describe the bug**
While setting up LaTeX project in VS Code and installing Strawberry Perl, I encountered issues with the antivirus.

**To Reproduce**
1. Go to https://strawberryperl.com/
2. Click on - 5.40.0.1 MSI 

**Screenshots**
![image](https://github.com/user-attachments/assets/82872990-5b15-41b2-84f4-f90c73f90ccb)
![image](https://github.com/user-attachments/assets/e22dcecc-d90e-4965-8e83-1ef949d2d14e)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - AntiVirus: McAfee

**Current resolution**
I exported the project on overleaf, with compiler as XeLaTeX

**Comment by santiviquez** [comment]
Mmm did you follow this tutorial?
 https://www.youtube.com/watch?v=4lyHIQl4VM8

It might just be an issue with the antivirus. I'm not exactly sure.

**Comment by AnshTanwar** [comment]
I followed the same tutorial. Yes I think the issue lies with certain antivirus software. Reference: https://github.com/StrawberryPerl/Perl-Dist-Strawberry/issues/123

**Comment by santiviquez** [comment]
Makes sense. If there is no malware in strawberry perl, then I think the best would be to ignore the antivirus? 🤷‍♂️ 

I'm closing this issue since there is nothing that we can do here.
