### ISSUE TITLE
Mean Forecast Error 

### ISSUE THREAD

**Issue by pratikwatwani** [NannyML/The-Little-Book-of-ML-Metrics#113]
**Metric's name**
Mean Forecast Error 

**Metric's category**
Time Series

**Metrics formula**
<img width="352" alt="Screenshot 2024-10-26 at 4 06 14 PM" src="https://github.com/user-attachments/assets/27ab0383-7ca1-4ec2-a8c0-727b4d2c76b9">

**Describe the metrics use cases, and any relevant references.**
MFE measures the average difference between predicted and actual values. It captures whether the model systematically over-predicts or under-predicts.

**Additional context**
FYI, MFE is different ni the sense that it specifically measures the bias in forecasts, rather than the overall accuracy or precision.

**Comment by santiviquez** [comment]
Good suggestion. We missed that one.

Would you like to take the lead on this one?

**Comment by pratikwatwani** [comment]
Yes, Of course!

**Comment by pratikwatwani** [comment]
Hi @santiviquez, I hope you’re doing well. Apologies for the delay—I was away due to surgery but am now back. Please allow me a couple of days to provide you with all the metric updates. I appreciate your understanding!

**Comment by santiviquez** [comment]
Hi @pratikwatwani no problem at all. Hope everything is alright!

**Comment by pratikwatwani** [comment]
Hi @santiviquez, thanks for checking in! I'm doing well now! I just opened a PR for the Dunn Index and would love your feedback. If it’s approved, I’ll proceed with updating the rest of the metrics by EOD! Of course whenever convenient for you! 😃
