### ISSUE TITLE
Gap Statistic

### ISSUE THREAD

**Issue by pratikwatwani** [NannyML/The-Little-Book-of-ML-Metrics#114]
**Metric's name**
Gap Statistic

**Metric's category**
Clustering

**Metrics formula**
<img width="311" alt="Screenshot 2024-10-26 at 4 10 22 PM" src="https://github.com/user-attachments/assets/18e4cd98-cfa8-4b1a-8f7e-f40b1c87c6fd">

**Describe the metrics use cases, and any relevant references.**
GS is used for clustering evaluation to help determine the optimal number of clusters in a dataset.

**Additional context**
Robert Tibshirani, Guenther Walther, Trevor Hastie, Estimating the Number of Clusters in a Data Set Via the Gap Statistic, Journal of the Royal Statistical Society Series B: Statistical Methodology, Volume 63, Issue 2, July 2001, Pages 411–423, https://doi.org/10.1111/1467-9868.00293

**Comment by santiviquez** [comment]
Thanks for the suggestion, @pratikwatwani, but I don't think Gap Statistic is relevant to the book. We prefer performance metrics, and this one is for determining the optimal number of clusters, not for assessing their quality.
