### ISSUE TITLE
Equal Opportunity Difference

### ISSUE THREAD

**Issue by pratikwatwani** [NannyML/The-Little-Book-of-ML-Metrics#115]
**Metric's name**
Equal Opportunity Difference

**Metric's category**
Bias & Fairness/Business

**Metrics formula**
Equal Opportunity Difference=
TPR(group 1) −TPR(group 2)

where 
TPR (True Positive Rate) = True Positives/(True Positives + False Positives)
​group 1 and 2 indicate different demographic groups

**Describe the metrics use cases, and any relevant references.**
EOD is used to assess if an ML model’s performance is consistent across different demographic groups (male vs female, low vs high income level, race etc) and ensuring that the model offers equal access to positive outcomes.

**Comment by santiviquez** [comment]
I believe this is duplicated https://github.com/NannyML/The-Little-Book-of-ML-Metrics/issues/84

**Comment by pratikwatwani** [comment]
Yes, you are right, I'll close it.
