### ISSUE TITLE
RMSLE formula

### ISSUE THREAD

**Issue by santiviquez** [NannyML/The-Little-Book-of-ML-Metrics#119]
We are missing the formula. It should be color-coded and described with arrows. Example of the formula for MSE
<img width="529" alt="381658224-496e36e5-9aea-4d54-bcad-297d34b9cc8c" src="https://github.com/user-attachments/assets/97084945-6940-42f0-a51c-bbcc3cc20ba5">

**Comment by chakka-guna-sekhar-venkata-chennaiah** [comment]
Hey @santiviquez . Im interested to do the work. Could you guide me the rest of detials?

**Comment by santiviquez** [comment]
Hi @chakka-guna-sekhar-venkata-chennaiah, I'm afraid this issue just got resolved in this recent PR: https://github.com/NannyML/The-Little-Book-of-ML-Metrics/pull/131

But feel free to tackle another one. This is the usual workflow for contributing.

1. Fork this repository
2. Clone the forked repo to your local env
3. Create a new branch before you make any
4. Make the desired changes
5. Commit and push your changes to your forked repo
6. Open a Pull Request from github.com

That is pretty much it. This video summarizes it nicely: https://www.youtube.com/watch?v=8lGpZkjnkt4

You might need to install latex on your own machine. In case you don't have it, check out this [instructions](https://github.com/NannyML/The-Little-Book-of-ML-Metrics/blob/main/CONTRIBUTING.md#getting-started).

For how to code the formula you can look at other ones in the latex documents.

Let me know if you need any help.
