### ISSUE TITLE
Explained Variance Score

### ISSUE THREAD

**Issue by santiviquez** [NannyML/The-Little-Book-of-ML-Metrics#128]
We are missing the formula. It should be color-coded and described with arrows. Example of the formula for MSE
<img width="529" alt="381658224-496e36e5-9aea-4d54-bcad-297d34b9cc8c" src="https://github.com/user-attachments/assets/97084945-6940-42f0-a51c-bbcc3cc20ba5">

**Comment by siddharth7113** [comment]
Hi @santiviquez I would like to  help with the issue, I have followed the instructions mentioned in contributing guidelines.

**Comment by siddharth7113** [comment]
Hi ,

I'm trying to build the main.tex file from the repository using MiKTeX (which I've ensured is fully updated) and VS Code. However, I'm encountering the following error:

```
Fatal Package fontspec Error: The fontspec package requires either XeTeX or LuaTeX.
(fontspec)                      You must change your typesetting engine to,
(fontspec)                      e.g., "xelatex" or "lualatex" instead of
(fontspec)                      "latex" or "pdflatex".

l.101 \msg_fatal:nn {fontspec} {cannot-use-pdftex}
```

It seems the build system defaults to pdflatex, which is incompatible with fontspec. Could you please confirm if the document is intended to be compiled with XeLaTeX or LuaTeX, and if there are any additional steps or configurations required for the build?

Thank you for your assistance!

Best regards,
Siddharth

**Comment by santiviquez** [comment]
Hi @siddharth7113, I guess you were able to resolve the issue, because I've just merged a successful PR from your side. But in case someone also has the same issue, indeed this project. uses XeLaTeX

**Comment by siddharth7113** [comment]
Hi @santiviquez ,

Thank you for merging the other PR! Yeah, I was able to resolve it by switching to XeLaTeX as you suggested. It worked perfectly once I updated the build settings to use the correct engine.

**Comment by santiviquez** [comment]
Great to hear that :)

**Comment by santiviquez** [comment]
Hi @siddharth7113 are you working on the Explained Variance formula?

**Comment by siddharth7113** [comment]
Hi @santiviquez ,  Sorry I forgot about this one, I was working on wMAPE,  due to  some work I would need few days to complete this one.

**Comment by santiviquez** [comment]
Ah, no worries at all! I was just checking if you were still interested in contributing to this one :)
