### ISSUE TITLE
Error in MAPE explanation

### ISSUE THREAD

**Issue by frsnjung** [NannyML/The-Little-Book-of-ML-Metrics#138]
**Metric's name**
MAPE

**Metric category**
regression

**Issue with current description**
The current description is wrong as it says: "MAPE penalizes negative errors **more** than positive errors".
![image](https://github.com/user-attachments/assets/7e7f9387-0999-40b4-9437-4cfbaca1a2e0)
The opposite is the case: models optimized on MAPE tend penalize negative errors less and thus prefering negative errors (i.e., an under-prediction, meaning y_hat - y_true < 0) because 1) denominator issue and 2) when forecasting positive quantities, the error is limited to 1 with a negative error/underforecast. (see this paper https://doi.org/10.1016/0169-2070(93)90079-3) 

Example: Given an underprediction with y_hat = 8 and y_true = 10, mape would be 0.2. On the other hand, given an overprediction, with y_hat = 10 and y_true = 8, mape would be 0.25. Thus, MAPE penalizes negative errors (under-prediction) less than positive errors.

**Suggestion**
Just change one word in the current sentence and change the the Formula to be consistent with the formula shown above. OLD: "MAPE penalizes negative errors **more** than positive errors". NEW: "MAPE penalizes negative errors **less** than positive errors".

This is all the adjustment needed.

**Comment by santiviquez** [comment]
Hi, @frsnjung regarding the image, I believe the one you shared is from the README, which is the old version. I need to update it.

If you check the online version, that should already be fixed.

<img width="294" alt="Screenshot 2024-12-03 at 13 44 31" src="https://github.com/user-attachments/assets/d95d7a31-291f-488c-8099-bf9583eb13e0">

Thanks for opening this!

**Comment by frsnjung** [comment]
Hi @santiviquez , yes I took this from the readme, forgot to write that.

**Comment by santiviquez** [comment]
I've just fixed the readme, thanks for reminding me about it :)
