### ISSUE TITLE
ROC AUC Formula

### ISSUE THREAD

**Issue by santiviquez** [NannyML/The-Little-Book-of-ML-Metrics#145]
We are missing the formula. It should be color-coded and described with arrows following the standards of other formulas present in the book.

Here is an example:
<img width="768" alt="Screenshot 2024-12-05 at 15 43 24" src="https://github.com/user-attachments/assets/a8c2963b-c3c9-4549-8fad-f936272a2af5">

**Comment by nakul-py** [comment]
Ohh. @Dhanunjaya-Elluri
