### ISSUE TITLE
MAPE — Mean Absolute Percentage Error

### ISSUE THREAD

**Issue by santiviquez** [NannyML/The-Little-Book-of-ML-Metrics#6]
**Metric's name**
Mean Absolute Percentage Error

**Metric's category**
Regression

**Comment by santiviquez** [comment]
We are only missing the formula.

In case someone would like to give me a hand by creating the latex formula, it should look like this:
<img width="590" alt="Screenshot 2024-10-30 at 11 11 28" src="https://github.com/user-attachments/assets/2cacfaa8-0f36-4e4f-b39c-7a02bff87ab9">

**Comment by minhduy13ly** [comment]
Hi, I also add the MAPE formula in the pull request #116. Please check it

**Comment by santiviquez** [comment]
Fixed by #116. Thanks to @minhduy13ly
