### ISSUE TITLE
Expected Cost (EC)

### ISSUE THREAD

**Issue by AnshTanwar** [NannyML/The-Little-Book-of-ML-Metrics#94]
**Metric's name** 
Expected Cost (EC)

**Metric's category**
Classification

**Metrics formula**
![image](https://github.com/user-attachments/assets/2276adb3-3e91-42e7-a1b5-4d9a807beeaf)

**Describe the metrics use cases, and any relevant references.**

Research paper for reference: https://arxiv.org/pdf/2209.05355 , https://openreview.net/forum?id=3mN9QNWArl

EC generalizes error rates and allows assigning different costs to each type of misclassification. It is particularly useful in applications like fraud detection where false negatives and false positives incur different costs. It helps in more practical evaluations of models compared to traditional metrics like accuracy or MCC. 

**Additional context**

Expected Cost (EC) is primarily a statistical metric rooted in decision theory and is frequently used in machine learning (ML)
Highly flexible, making it applicable in both binary and multi-class classification problems.

**Comment by santiviquez** [comment]
Thanks for the great suggestion @AnshTanwar! Would you like to take the lead on this one?

**Comment by AnshTanwar** [comment]
Yes @santiviquez, I will be happy to work on this metric

**Comment by santiviquez** [comment]
Great! Let me know if you need any guidance.

**Comment by AnshTanwar** [comment]
Hey @santiviquez want some guidance, Should I follow the same pattern and flow of the book , like 2 pages per metric. Can I try with something more which can extend the number of pages. I think this metric requires more explanation to fully justify it.

**Comment by santiviquez** [comment]
Closed by #104
